name: nodejs-app-deploy

on:
  workflow_dispatch:
  push:
    branches:
      - feat/aws
env:
  ECR_REGISTRY: 012535859612.dkr.ecr.ap-northeast-2.amazonaws.com
  ECR_REPOSITORY: nyongnyong-ecr
  APPLICATION_NAME: nyongnyong
  ENVIRONMENT_NAME: Nyongnyong-env
  AWS_REGION: ap-northeast-2
  GIT_SHA: ${{ github.sha }}

jobs:
  deploy-prod:
    name: Deploy to production
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.BE_STUDENT_KEY }}
          aws-secret-access-key: ${{ secrets.BE_STUDENT_SECRET }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Create .env file
        run: |
          touch .env
          echo DB_HOST=${{ secrets.BE_STUDENT_DB_HOST }} >> .env
          echo DB_USERNAME=${{ secrets.DB_USERNAME }} >> .env
          echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
          echo DB_DATABASE=${{ secrets.DB_DATABASE }} >> .env
          echo DB_PORT=${{ secrets.DB_PORT }} >> .env
          echo JWT_REFRESH_TOKEN_SECRET=${{ secrets.JWT_REFRESH_TOKEN_SECRET }} >> .env
          echo JWT_ACCESS_TOKEN_SECRET=${{ secrets.JWT_ACCESS_TOKEN_SECRET }} >> .env
          echo JWT_ACCESS_TOKEN_EXPIRATION_TIME=${{ secrets.JWT_ACCESS_TOKEN_EXPIRATION_TIME }} >> .env
          echo JWT_REFRESH_TOKEN_EXPIRATION_TIME=${{ secrets.JWT_REFRESH_TOKEN_EXPIRATION_TIME }} >> .env
          echo KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }} >> .env
          echo KAKAO_SECRET=${{ secrets.KAKAO_SECRET }} >> .env
          echo GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} >> .env
          echo GOOGLE_SECRET=${{ secrets.GOOGLE_SECRET }} >> .env
          echo NAVER_CLIENT_ID=${{ secrets.NAVER_CLIENT_ID }} >> .env
          echo NAVER_SECRET=${{ secrets.NAVER_SECRET }} >> .env
          echo OPEN_SEARCH_URL=${{ secrets.OPEN_SEARCH_URL }} >> .env
          cat .env

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
          GIT_SHA: ${{ env.GIT_SHA }}
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD_HH-mm-ss
          utcOffset: '+09:00'

      - name: Generate deployment package
        run: |
          mkdir -p deploy
          cp be-student-Dockerrun.aws.json deploy/Dockerrun.aws.json
          cd deploy && zip -r deploy.zip .

      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.BE_STUDENT_KEY }}
          aws_secret_key: ${{ secrets.BE_STUDENT_SECRET }}
          application_name: ${{ env.APPLICATION_NAME }}
          environment_name: ${{ env.ENVIRONMENT_NAME }}
          version_label: egg-docker-${{steps.current-time.outputs.formattedTime}}
          region: ${{ env.AWS_REGION }}
          deployment_package: deploy/deploy.zip
          wait_for_environment_recovery: 200
